- hosts: localhost
  pre_tasks:
  - name: Update dnf
    dnf:
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core.yml
    - include: tasks/git.yml
    - include: tasks/zsh.yml
